name: Linter

on:
  pull_request:
    paths:
      - '**.go'
jobs:
  golangci-lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2.4.0
      - name: Set up Go 1.17
        uses: actions/setup-go@v2.1.4
        with:
          go-version: 1.17
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v2.5.2
        with:
          version: v1.42.1
          args: --timeout=10m
          skip-go-installation: true
